/**
 * Copyright (c) 2012-2017, www.tinygroup.org (luo_guo@icloud.com).
 * <p>
 * Licensed under the GPL, Version 3.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * <p>
 * http://www.gnu.org/licenses/gpl.html
 * <p>
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.tinygroup.jdbctemplatedslsession;

import org.apache.commons.collections.map.CaseInsensitiveMap;
import org.tinygroup.jdbctemplatedslsession.ConfigurationBuilder.TableConfig;
import org.tinygroup.tinysqldsl.KeyGenerator;

import java.util.Map;

/**
 * 配置对象
 *
 * @author renhui
 */
public class Configuration {
    public static final int DEFAULT_MAX_START = -1;
    public static final int DEFAULT_MAX_LIMIT = -1;
    // key:表名,value:表配置对象
    private Map<String, TableConfig> tableConfigMap = new CaseInsensitiveMap();
    // 默认的主键生成器
    private KeyGenerator defaultKeyGenerator;
    private boolean defaultAutoKeyGenerator = true;
    private boolean canCount = true;//分页查询时，是否执行count语句的标记
    private int startMaxValue = DEFAULT_MAX_START;

    private int limitMaxValue = DEFAULT_MAX_LIMIT;


    public KeyGenerator getDefaultKeyGenerator() {
        return defaultKeyGenerator;
    }

    public void setDefaultKeyGenerator(KeyGenerator defaultKeyGenerator) {
        this.defaultKeyGenerator = defaultKeyGenerator;
    }

    public boolean isDefaultAutoKeyGenerator() {
        return defaultAutoKeyGenerator;
    }

    public void setDefaultAutoKeyGenerator(boolean defaultAutoKeyGenerator) {
        this.defaultAutoKeyGenerator = defaultAutoKeyGenerator;
    }

    public void putTableConfig(TableConfig tableConfig) {
        tableConfigMap.put(tableConfig.getTableName(), tableConfig);
    }

    public Class getPojoClass(String tableName) {
        TableConfig tableConfig = tableConfigMap.get(tableName);
        if (tableConfig != null) {
            return tableConfig.getType();
        }
        return null;
    }

    public boolean isAutoGeneratedKeys(String tableName) {
        TableConfig tableConfig = tableConfigMap.get(tableName);
        if (tableConfig != null) {
            return tableConfig.isAutoGeneratedKeys();
        }
        return defaultAutoKeyGenerator;
    }

    public KeyGenerator getKeyGenerator(String tableName, String keyName) {
        TableConfig tableConfig = tableConfigMap.get(tableName);
        KeyGenerator keyGenerator = null;
        if (tableConfig != null) {
            keyGenerator = tableConfig.getKeyGenerator(keyName);
        }
        if (keyGenerator == null) {
            keyGenerator = defaultKeyGenerator;
        }
        return keyGenerator;
    }

    public boolean isCanCount() {
        return canCount;
    }

    public void setCanCount(boolean canCount) {
        this.canCount = canCount;
    }

    public int getStartMaxValue() {
        return startMaxValue;
    }

    public void setStartMaxValue(int startMaxValue) {
        this.startMaxValue = startMaxValue;
    }

    public int getLimitMaxValue() {
        return limitMaxValue;
    }

    public void setLimitMaxValue(int limitMaxValue) {
        this.limitMaxValue = limitMaxValue;
    }
    
    public boolean needCheckStartValue(){
    	if(startMaxValue==DEFAULT_MAX_START){
    		return false;
    	}
    	return true;
    }

    public boolean needCheckLimitValue(){
    	if(limitMaxValue==DEFAULT_MAX_LIMIT){
    		return false;
    	}
    	return true;
    }

}
